version: "3"

services:
  dashboard:
    build: .
    container_name: shogun_dashboard
    image: lucasmsp/shogun-dashboard:latest
    volumes:
      - ./input_data:/opt/input_data/
      - ./output_data:/opt/output_data/
    networks:
      - default
    ports:
      - 8080:8080
    command: python3 app.py --host 0.0.0.0 --port 8080
    environment:
      - ADMIN_PASSWORD=admin  # replace this password
      - CRON_EXPRESSION=*/1 * * * *
      - SHODAN_FOLDER=/opt/input_data/
      - RESULT_FOLDER=/opt/output_data/
      - POSTGRES_URL=postgres:5432
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=StrongPassword.123  # replace this password
      - FLASK_SECRET=XXXXXXXXXXXXXXXX  # replace this password
      # A good recipe to generate FLASK_SECRET is copy the content of `import os; os.urandom(24)`
    depends_on:
      postgres:
        condition: service_healthy

  scheduler:
    build: .
    container_name: shogun_scheduler
    image: lucasmsp/shogun-dashboard:latest
    volumes:
      - ./input_data:/opt/input_data/
      - ./output_data:/opt/output_data/
    networks:
      - default
    ports:
     - 4040:4040
    command: python3 -m project.scheduler --mode latest
    environment:
      - CRON_EXPRESSION=*/1 * * * *
      - SPARK_UI_PORT=4040
      - SPARK_VCORES=4
      - SPARK_MEMORY=4g  
      - SHODAN_FOLDER=/opt/input_data/
      - RESULT_FOLDER=/opt/output_data/
      - TLHOP_DATASETS_PATH=/opt/output_data/tlhop_datasets/

  postgres:
    container_name: shogun_postgres
    image: postgres:18.4
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - 5432:5432
    networks:
      - default
    environment:
      - POSTGRES_PASSWORD=StrongPassword.123  # replace this password
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 3s
      timeout: 3s
      retries: 10

volumes:
  postgres_data:
    driver: local
