version: "3"

services:
  dashboard:
    build: .
    image: lucasmsp/tlhop-dashboard:latest
    volumes:
      - ./input_data:/opt/input_data/
      - ./output_data:/opt/output_data/
    networks:
      - default
    ports:
    - 8080:8080
    - 4040:4040
    #command: ["python3", "app.py"]
    command: ["python3", "app.py", "dev"]
    environment:
      # each 1 minute  
      - CRON_EXPRESSION=*/1 * * * *
      # "0 8 * * *"  # each day at 8h AM
      - SPARK_UI_PORT=4040
      - SPARK_VCORES=6
      - SPARK_MEMORY=4g  
      - SHODAN_FOLDER=/opt/input_data/
      - RESULT_FOLDER=/opt/output_data/
      - TLHOP_DATASETS_PATH=/opt/output_data/tlhop_datasets/
    env_file: local/env
    depends_on:
      postgres:
        condition: service_healthy

#    restart: always

  postgres:
    container_name: tlhop_postgres
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default
    env_file: local/env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 3s
      timeout: 3s
      retries: 10

volumes:
  postgres_data:
    driver: local




